import './globals.css'
import { Montserrat  } from '@next/font/google'

const montserrat = Montserrat({
  weight:["400", "700"],
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`${montserrat.className} mx-32 my-12`}>
        {/* <nav>
          <h2>Logo</h2>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
        </nav> */}
        {children}</body>
    </html>
  )
}
